### ISSUE TITLE
Forest editor brushes and itemData bugs

### ISSUE THREAD

**Issue by Duion** [GarageGames/Torque3D#1936] opened 2017-01-31 16:33 UTC
There seems to be a bug in the forest editor that appears when you hit after having added a certain amount of items to the forest editor.
After that weird things happen, like it always selects two items from the managedItemData list and when you delete one you also delete the other, in addition to that it adds random items in the brushes file, ok those are not random, but from the other item that gets selected when you select one from the managedItemData and it does not create the one that you selected on double clicking it, but the one that got automatically selected as well, when you select another one.
Here is a video so you can understand whats happening:
http://duion.com/files/temp/bugs/forest_editor_buggared.mp4

I downloaded the 3.10 rc2 version as a blank base, then I added my old levels over it, first copied over that one http://opengameart.org/content/konserian-highlands-set and then copied over that one http://opengameart.org/content/uberpack-1
After that I had my old level packs back in with lots of forest and forest items.
The bug is almost 4 years old now, but I need a solution now, since I don't want to risk running into it again when I will add more trees.

**Comment by Duion** [comment] 2017-01-31 21:26
And when I delete a brush the whole engine crashes to desktop instantly.

**Comment by Areloch** [comment] 2017-02-01 02:33
Looks like something going on with the selection logic for the tree view control, not the forest/item data stuff. I'll see if I can drum up a fix.

**Comment by Areloch** [comment] 2017-02-03 06:29
Alright, figured out what triggers it to occur.

Go into tools/forestEditor/forestEditorGui.gui and find the ForestEditMeshTree object. find the 'compareToObjectID' field and set it to 0.

This is causing an issue where it tries to do a secondary test on selected items by the associated object id for that item in the tree. However, because the forest item ids are low, it can cause a false positive and match the real selected item index with the forestItemData's object ID. Making it so we don't even bother with that check seems to have prevented the double-selection issue.

Let me know if that fixes the problem for you too and if so I'll get a PR in to fix it.

**Comment by Duion** [comment] 2017-02-03 08:23
Great that fixes it.
Some other issues are, that the game always crashes to desktop when I press the "del" key on the keyboard in order to delte an entry in either the meshes or brushes. Using the trashcan symbol in the editor however works. So maybe you are not supposed to use the hotkey, but I cannot imagine that.
Another small issue is on the brushes, when you try to select multiple brushes holding the shift key, it randomly selects som brushes above it as well, similar to the initial bug with the meshes, but only using shift, but I can live with that bug.

But your change fixes the biggest issue, so it can be rolled in.

**Comment by Areloch** [comment] 2017-02-04 07:02
Looked into these.

For the selection oddity, shift is 'range selection', ie, it selects everything between the two selected items. if you hold ctrl, THAT's your regular multiselect. Maybe those should be flipped around for more consistency with other editing means, but it's not actually broken in this case.

For the deletion, the issue is that if you aren't in select mode, the editor intercepts the delete keybind and crashes because it's not the active tool, so when it goes to create an undo event for the delete, there's a null reference exception.

I can correct that easily enough so delete only actually kicks off when in select mode, but that complicates trying to use delete with the brush/mesh items because if you hit delete and are in select mode, but also have an item in one of the trees selected, which delete command should apply? Should it delete the selected item in the map? Should it delete the brush/mesh tree item?

For now, I'll commit the compareToObjectID and select-tool crash error to fix those issues. You can still delete the brush/mesh items by clicking the garbage icon'd button above the trees.

**Comment by Areloch** [comment] 2017-02-05 05:10
Fixed with #1942

**Closed by Areloch** 2017-02-05 05:10 UTC
Labels: Bug
