### ISSUE TITLE
Editor crashes after lighting change

### ISSUE THREAD

**Issue by Duion** [GarageGames/Torque3D#1314] opened 2015-05-19 22:27 UTC
I get a lot of crashes when using the editor with the newest branch, it crashes when you switch to the editor and back to the game again after you changed some stuff in the editor and it crashes if you press F11 again in the editor and sometimes it crashes when you want to exit.

There is always the following lines at the end of the console log:

Win32Window::WindowProc - resetting device due to window size change.
GFXPCD3D9Device::reset - depthstencil 123f3af8 has 3 ref's

**Comment by eightyeight** [comment] 2015-05-20 00:07
Newest branch being `development` or `release-3.7`?

**Comment by John3** [comment] 2015-05-20 00:44
I have the same question, what is the newest branch?

**Comment by Duion** [comment] 2015-05-20 09:22
I used both.

**Comment by John3** [comment] 2015-05-21 01:58
lol well the question is for daniel, what is the newest?

**Comment by eightyeight** [comment] 2015-05-21 02:51
`release-3.7` has just bugfixes for the 3.7 release, whereas `development` has continuing changes for 3.8. The 3.7 branch is currently newer, and probably more stable thanks to some important fixes. It will be merged into `development` when we release 3.7.

**Comment by Areloch** [comment] 2015-05-27 18:53
My suggestion on this, since there's not much info in the issue as-is. Run it in debug, and see if you can get the crash to happen again. Then copy and post the call stack so we can have a better idea of where exactly the crash is occurring.

**Comment by John3** [comment] 2016-05-08 22:19
Hi Duion. Can you test again? Have you still have editor crashes? 

Shared the steps to try to replicate the error. 

If not, can we consider to close this? Have one year already.

**Comment by Duion** [comment] 2016-05-09 07:37
I did not upgrade to the latest development branch, but I found out, that the crash happens, if you change something that has to do with lighting, like the sun object or scattersky and then try to switch to game. So as long as you stay in editor it is fine, but it crashes if you close the editor.

**Comment by John3** [comment] 2016-05-09 19:19
Ok, I try to replicate what are you saying. I tested in a clean T3D created a new project with the full template. Please can you see the video and tell me if executed the steps correctly?

<a href="https://drive.google.com/file/d/0B9GUwtDHCp_eQm1nQ29uenkzMlU/view?usp=drivesdk">https://drive.google.com/file/d/0B9GUwtDHCp_eQm1nQ29uenkzMlU/view?usp=drivesdk</a>

**Comment by Duion** [comment] 2016-05-09 20:51
Yes, that is what crashes it for me. But I'm not using the actual version, maybe it has been fixed, or the reason is, that my build is heavily modifed, since I'm not using stock T3D anymore.

I tried to reproduce it myself again and it immediately crashed after just changing the skybrightness.
These are the last entries in console:
   Entering Editor::close(Editor, PlayGui)
      Entering [CanvasCursorPackage]GuiCanvas::setContent(Canvas, PlayGui)
         Entering EditorGui::onUnsetContent(18021, 17042)
            Entering EditorGui::detachMenus(18021)
               Win32Window::WindowProc - resetting device due to window size change.
               GFXPCD3D9Device::reset - depthstencil 12965798 has 3 ref's
               --- Resetting D3D Device ---
            Leaving EditorGui::detachMenus() - return

**Comment by John3** [comment] 2016-05-09 21:17
@Areloch I have a doubt with this kind of issue. How can we treat it? 

I mean duion said that he have a heavily modified version of T3D.... May be his "duion version" has the bug not necessarily T3D community have the bug.

Just a opinion here, I think will be better in the future that someone can confirm the new open issue, just to be sure you know.

**Comment by Duion** [comment] 2016-05-10 09:54
I just tested with a precompiled release build of Torque3D 3.8 to make sure it is not a result of my changes, I opened editor in blank room level, removed the sun, added scatterSky, changed the sky brightness and pressed F11 again to deactivate the editor, at that moment the game crashed.
After another test I realized that this issue does not always happen, as I opened the empty terrain level instead with the desert, it did not crash, when changing scatterSky brightness.
So I tested if it is related to an interaction to other level objects and deleted all objects in the scene except the levelInfo and scatterSky, but it still crashed.

**Comment by John3** [comment] 2016-05-10 13:46
Thanks duion for the information.

I did the same test as you describe in both versions precompiled T3D 3.8 and compiled T3D 3.8. I use VS2010 and defaults options from the project manager. I don't saw the crash.

Ok as I understand is not you T3D version or T3D community version, right? So maybe is your PC, compatibility issue or something.

Do the following:
- You have antivirus enable? Disable and do the test
- You have firewall enable? Disable and do the test. (Disable both)
- Configure the .exe with Windows 7 comparability mode if you are using a newer version of Windows.

Please Duion can you shares the following information?
- What version of Windows or Linux are you using?
- What driver version are you using for you graphics card?
- What model is you graphics card?
- Are you using OpenGL or DirectX?
- What DirectX are you using 9? 11?
- What resolution are you using?

If you see a crash shared the console.log.

**Comment by Duion** [comment] 2016-05-10 14:18
It is not the antivirus or firewall and I have Windows 7. My graphics card is Amd R9 280x and I'm using DirectX9. Resolution is the default settings, 1024x768 windowed mode.

**Comment by John3** [comment] 2016-05-10 14:56
OK I will check you graphic card maybe is you AMD I have alot issues with that in the past because of that I change to nvidia

**Comment by John3** [comment] 2016-05-10 16:58
Ok i did a research, and that model have a few issue reported with game crashed, a few people resolved the issue reinstalling the graphic drivers. I mean completely uninstalled and then cleaning the system with ccleaner or something, and then installing the last driver.

- Try disable any overclocking on your card.
- Turn off MSAA
- Try disable the AMD Gaming Evolved "In Game Overlay".
- Try this lowers you texture details from T3D setting with filtering off

- Compile you game with dx11 instead of dx9 here we can insulate a little more the problem.
- Compile you game with OpenGL, we can insulate a little more the problem, to be sure if the problem is with dx9.

BTW Can you change the title? to something more descriptive? referring to the lighting problem you have.

**Closed** 2016-11-03 04:59 UTC
Labels: Bug
