### ISSUE TITLE
Level Output crash (development branch)

### ISSUE THREAD

**Issue by John3** [GarageGames/Torque3D#1232] opened 2015-03-01 14:45 UTC
testing development branch. 

Project Manager 2.2 (Binary)
- Bullet
- OpenGL Rendering
- Template Full

Development Branch (Compiled with VS2010)
In-game:
 - Option Intel HD OpenGL
- Quality: any
- Filtering/Aliasing: any
- Level Outpost

Crash in "Loading Objects"

Console.log - http://pastebin.com/THv62Puy

**Comment by Azaezel** [comment] 2015-03-01 23:58
Verified there's a general crash in development head that it would at first check seems to have cropped up in the last 2-3 days worth of commits. Reproduction requires taking directory re-creation from the top (initial assumption is something gone pearshaped with .cached.dts). Attempting to further isolate the issue.

**Comment by LuisAntonRebollo** [comment] 2015-03-01 23:59
@JeffProgrammer and me can confirm the crash :(

**Comment by Azaezel** [comment] 2015-03-02 01:15
quick followup: looks like the culprit is buried someplace in https://github.com/GarageGames/Torque3D/commit/33fcc59543a81acfe12661bb0c6455a865476794

**Comment by eightyeight** [comment] 2015-03-02 01:58
Shoot. Check the files that conflicted - there was a conflict I fixed that looked like some code in `compiledEval.cpp` had been deleted upstream, so I removed it, but maybe that was the wrong idea. Actually, looking through the changes now, it seems completely fine. Hmm.

**Comment by eightyeight** [comment] 2015-03-02 11:08
Fixed by #1234.

**Closed by eightyeight** 2015-03-02 11:08 UTC
Labels: Bug / fix
