### ISSUE TITLE
LevelInfo fog shenanigans

### ISSUE THREAD

**Issue by eightyeight** [GarageGames/Torque3D#822] opened 2014-10-08 23:00 UTC
Reports that the LevelInfo fog was broken by [this](https://github.com/GarageGames/Torque3D/pull/362). Re-evaluate the purpose for the change and whether it should be reverted.

**Comment by Areloch** [comment] 2016-05-09 16:02
It's "working as intended" as per my response on #1043

Less a 'not working properly' and more of a 'works in a confusing way if using scattersky'. Going to close this one and we can discuss a better way to approach fog handling in the other ticket.

**Closed by Areloch** 2016-05-09 16:02 UTC
Labels: Bug
