### ISSUE TITLE
Export to collada bug

### ISSUE THREAD

**Issue by razvanab** [GarageGames/Torque3D#467] opened 2013-08-13 16:00 UTC
Exported collada object from torque3d editor fails to load in blender.

The reason seems to be the format:
under 3d max the file is imported correctly if Autodesk collada is selected.

**Comment by soloflareinteractive** [comment] 2015-04-04 19:40
I seem to be having the same problem. I cannot seem to export Collada models from the engine :(

**Comment by John3** [comment] 2016-11-23 18:54
I did a quick look and I see two problems into the exported mesh. 1) the coordinates are together. 2) and the tag "<library effects>" is damaged or maybe too old, this prevent to load the mesh into Blender3D. I did a few test and I can load any model into Blender3D 2.78a using T3D dev commit commit on Nov 22, 2016 cfb88b, from sketch tool covex models or other .dae models (like station01.dts, healthpatch.dts, healthkit.dts, or other more complex models.) 

So now I can fix manually any model, I need to dig more into this issue.

**Comment by John3** [comment] 2016-11-25 16:52
Hi, this issue #467 is not a bug. This is an old collada format, using colladaMax (if I not wrong is version 1.1.0), and is exported correctly under 3D Studio Max 2009 (Not tested in other version), I belive this was intented this way. So, we need to use a new collada format to work under newest Blender3D. For this we can use as someone said use a converter like "Autodesk FBX 2013.3 Converter" but we can use any converter like this online "http://www.greentoken.de/onlineconv/", because the old colladaMax format its converterted to a new collada format and then we can load into blender3D.

Since T3D v3.0 has a bug introduce by TinyXML in the following commit Mar 13, 2013 512f0f1. The mesh coordinates are toghether, preventing to load the mesh and throwing an error.

I think we need close this issue and open two issues with a best description of the collada problem, 1) for the coordinate bug, if we fix this we can start using the "export to collada" function of T3D and then using any "3D asset exchange exporters/converter". And 2) open other issue for the update the old colladaMax format exporter, to a new openCollada format.

**Comment by razvanab** [comment] 2016-11-25 17:02
Can we just replace Collada exporter with the obj format since only the static mesh is what we need ?

**Comment by John3** [comment] 2016-11-26 19:32
OK, the collada exporter is fixed, I tested in blender3d 2.78a and 3D Studio Max 2009. Please test the Sketch Tool and export, or use you already dts files like station01, healthkit, Cheetah_Turret, etc or any model you have. You can download a executable from here [T3D_ColladaExporter](https://drive.google.com/file/d/0B9GUwtDHCp_eYlpuZHQ1aEhGRmM ) (15MB)

**Comment by John3** [comment] 2016-12-10 14:15
This issue can be closed. If anyone wan to test without compile just download from here:

https://github.com/John3/Torque3D_Unofficial/releases/tag/v1.0.14

**Closed** 2017-01-20 06:49 UTC
Labels: Bug
