### ISSUE TITLE
Bullet triggers assert on Outpost Mission

### ISSUE THREAD

**Issue by velteyn** [GarageGames/Torque3D#1462] opened 2015-11-14 15:25 UTC
Hi all,
I activated the bullet support but in debug it triggers an assert on OUTPOST Mission, I'm using V3.8 branch

![immagine](https://cloud.githubusercontent.com/assets/1019294/11164288/27d7f836-8aec-11e5-971b-f0e0c6047987.png)
 btAssert(length() != btScalar(0));

see file attach
![immagine2](https://cloud.githubusercontent.com/assets/1019294/11164296/56a39a58-8aec-11e5-9bbb-2afa5c617e04.png)

**Comment by Azaezel** [comment] 2015-11-14 15:40
Odd... sure you've got https://github.com/GarageGames/Torque3D/pull/1361/files your end? That was the cause of precisely that last go-around...

**Comment by velteyn** [comment] 2015-11-14 15:56
Watch  this screen, have I something wrong ? (I'm a git noob so I'm not sure)
![immagine](https://cloud.githubusercontent.com/assets/1019294/11164444/9c6381da-8af0-11e5-801e-75d970f4a032.png)

**Comment by Azaezel** [comment] 2015-11-14 16:15
What do you get when it goes debug-fatal for displacementTest if you replace that spot in the source with:

F32 displacementTest = disp.length();
if (displacementTest>0.0001)
      mGhostObject->convexSweepTest( mColShape, start, end, callback, 0.0f );

**Comment by velteyn** [comment] 2015-11-14 16:22
I changed the code as suggested but same result

screen : 
![immagine](https://cloud.githubusercontent.com/assets/1019294/11164544/46afc182-8af4-11e5-9795-da2eceb31964.png)

**Comment by Azaezel** [comment] 2015-11-14 16:25
and what is the *value*

**Comment by velteyn** [comment] 2015-11-14 16:27
0.0737474337 but is not easy to catch, sometimes it's 0.0000

**Comment by velteyn** [comment] 2015-11-14 16:30
0.455766380 Now it is the value BEFORE assert

**Comment by Azaezel** [comment] 2015-11-14 16:31
0.0737474337 but is not easy to catch, sometimes it's 0.0000 these are both when it is breaking your end?

**Comment by velteyn** [comment] 2015-11-14 16:32
I have to correct me , its never 0.0000.. I did a wrong reading

**Comment by velteyn** [comment] 2015-11-14 16:33
It starts with other values but I have no asserts ! Then I have 0.455766380 , and I obtain the assert if I hit play on debug

**Comment by velteyn** [comment] 2015-11-14 16:36
If I hit continue I obtain 0.0737474337, then on play I obtain another assert

**Comment by Azaezel** [comment] 2015-11-14 16:44
After the break doesn't matter. only the values in the stacktrace when it is acting up. 32 bit compile just finished. Will attempt replication.

**Comment by Azaezel** [comment] 2015-11-14 16:54
Ok. I see what happened. it's trigerign due to the *other* convexSweepTest https://github.com/GarageGames/Torque3D/blob/2044b2691e1a29fa65d1bdd163f0d834995433ce/Engine/source/T3D/physics/bullet/btPlayer.cpp#L344

Try sticking the same if (disp.length()>0.0001) in front, and if that works for you as well, will go ahead and PR that.

**Comment by velteyn** [comment] 2015-11-14 16:57
GREAT !!! IT WORKED !! Thank you !! Mission started !!

**Comment by Areloch** [comment] 2015-11-17 04:04
Fixed via #1463

**Closed by Areloch** 2015-11-17 04:04 UTC
