### ISSUE TITLE
Editor ribbon cannot be expanded once collapsed

### ISSUE THREAD

**Issue by eightyeight** [GarageGames/Torque3D#1292] opened 2015-04-29 23:58 UTC
Clicking the little arrow on the ribbon to collapse the icons works, but clicking it again to expand them fails with a console message. EDIT: introduced in #1092, I think. EDIT: reverting 61e106251 made no difference. Hmm.

**Comment by eightyeight** [comment] 2015-05-09 04:18
There's code that looks like this:

    %this.setExtent((29 + 4) * %count + 12, 33);

Which is somehow causing `setExtent` to set the extent to 33, 33. Um, what? It works if I do this:

    %x = (29 + 4) * %count + 12;
    %this.setExtent(%x, 33);

And also if I change `setExtent` to take `String`s instead of `const char*`s. @jamesu could this be one of yours?

**Comment by jamesu** [comment] 2015-05-13 17:22
I'll have a look and see whats going on

**Comment by jamesu** [comment] 2015-05-15 09:18
Ok the problem is with these fancy DefineConsole* methods, when it unmarshalls and converts those two values to strings according to the function definition it uses the same buffer (i.e. Con::getReturnBuffer) to store the value, thus each value becomes 33.

Accepting String instead is a reasonable workaround, though really the console code should print these values to a temporary buffer space since quite a few functions seem to use const char* as parameters.

I'll see if I can cook up a good workaround.

**Comment by jamesu** [comment] 2015-05-15 09:28
Ok I have a fix, just testing and I'll submit a PR.

**Comment by eightyeight** [comment] 2015-05-15 09:48
Awesome, really appreciate it! I submitted the String fix in case you didn't have time to look into it, but we have a couple of other things to do for 3.7 so hopefully we can get the proper fix in. I'm surprised this hasn't turned up as a problem elsewhere.

**Comment by jamesu** [comment] 2015-05-15 11:36
Pushed fix. Ideally this problem should be resolved in a better way but this will do for now.

**Comment by eightyeight** [comment] 2015-05-15 12:50
Thanks for that. I'm going to test this and revise the other outstanding PRs tomorrow.

**Closed** 2015-05-28 10:36 UTC
Labels: Bug / fix
